add_library(Problem
    PECGrating.cc
    PECGrating.h
    PECGratingReduced.cc
    PECGratingReduced.h
    PECGratingReducedML.cc
    PECGratingReducedML.h
    ParametricProblem.cc
    ParametricProblem.h
    RiemannLiouvilleProblem.cc
    RiemannLiouvilleProblem.h
)

target_include_directories(Problem
    PUBLIC
        ${CMAKE_CURRENT_SOURCE_DIR}
)

target_link_libraries(Problem
    PRIVATE
        Operators
        EmpiricalInterpolation
        msg_lib
        QMC
        progressbar
        Integration
        GreenFunc
    PUBLIC
        utils_lib
)
